year: '2021'
site_name:
  en: Ian M. Nesbitt
site_source: iannesbitt/website
site_author: Ian Nesbitt
keywords: 'science, geoscience, geophysics, geomorphology, software, open-source'
language: en
site_language_menu:
  "\U0001F1EC\U0001F1E7": /
site_menu:
  en:
    Home: /
    About: /#about
    Publications: /publications.html
    CV: https://github.com/iannesbitt/cv/raw/main/_output/cv.pdf
    Posts: /#posts
    Contact: /#contact
contact:
  links:
  - icon: fas fa-envelope
    text: ian.nesbitt@gmail.com
    url: mailto:ian.nesbitt@gmail.com
  - icon: fab fa-orcid
    text: ORCiD
    url: https://orcid.org/0000-0001-5828-6070
  - icon: fas fa-book
    text: Google Scholar
    url: https://scholar.google.com/citations?user=voGZIlIAAAAJ&hl=en
  - icon: fab fa-researchgate
    text: ResearchGate
    url: https://www.researchgate.net/profile/Ian_Nesbitt3
  - icon: fab fa-linkedin
    text: LinkedIn
    url: https://www.linkedin.com/in/ianmnesbitt
  - icon: fab fa-github
    text: 'GitHub: @iannesbitt'
    url: https://github.com/iannesbitt
  - icon: fab fa-twitter
    text: 'Twitter: @paleosurface'
    url: https://twitter.com/paleosurface
  - icon: fa fa-graduation-cap
    text: 'Climate Change Institute profile'
    url: https://climatechange.umaine.edu/people/ian-nesbitt/
  - icon: fa fa-graduation-cap
    text: 'School of Earth and Climate Sciences profile'
    url: https://umaine.edu/earthclimate/people/ian-nesbitt/
  title:
    en: Links
ignore:
  - README.md
  - Makefile
